name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} #hostname of server
          username: ${{ secrets.SSH_USERNAME }} #username login to server
          key: ${{ secrets.SSH_PRIVATE_KEY }} #password login to server
          script: | # run with multiple script
            cd /home/duccao/project/guest/ats-pomodoro-nextjs ; npm install ; npm run build
