name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          if [ $GITHUB_REF = "refs/heads/dev_v2_son" ]; then
            "cd /path/to/your/app && git pull origin staging && npm install && npm run build && pm2 reload your-staging-app"
          elif [ $GITHUB_REF = "refs/heads/main" ]; then
            "cd /home/duccao/project/guest/ats-web-pomodoro && git pull origin main && npm install && npm run build && pm2 reload test-cd"
          fi
