name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: executing remote ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -la
            node -v
          host: ${{ secrets.SSH_HOST }}
          user: duccao
          key: ${{ secrets.SSH_PRIVATE_KEY}}
