name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 157.230.242.237 # \
          username: duccao
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home
            pm2 list
